
- name: Install prerequisites
  hosts: nodes
  become: yes
  tasks:
    - name: Ensure Go is installed
      ansible.builtin.command:
        cmd: yum install golang -y

    - name: Ensure rpm-build is installed
      ansible.builtin.command:
        cmd: yum install rpm-build -y

    - name: Ensure git is installed
      ansible.builtin.command:
        cmd: yum install git -y

- name: Create rpmbuild directory structure
  hosts: nodes
  become: false

  tasks:
    - name: Create top-level rpmbuild directories
      ansible.builtin.file:
        path: "{{ rpmbuild_home }}/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - BUILD
        - RPMS
        - SOURCES
        - SPECS
        - SRPMS

- name: Copy Cluster Exporter files
  hosts: nodes
  become: false
  tasks:
    - name: Clone Cluster Exporter repository
      ansible.builtin.git:
        repo: "{{ repo_path }}"
        dest: "{{ source_path }}"
        version: "main"
        force: yes
        update: yes

    - name: Create tar.gz
      ansible.builtin.archive:
        path: "{{ source_path }}"
        dest: "{{ rpmbuild_home }}/SOURCES/{{ exporter_label }}.tar.gz"
        format: gz

    - name: Copy default options file
      ansible.builtin.copy:
        src: "{{ source_path }}/systemd/prometheus-cluster-exporter.options"
        dest: "{{ rpmbuild_home }}/SOURCES/prometheus-cluster-exporter.options"
        mode: '0644'
        remote_src: yes

    - name: Copy systemd service file
      ansible.builtin.copy:
        src: "{{ source_path }}/systemd/prometheus-cluster-exporter.service"
        dest: "{{ rpmbuild_home }}/SOURCES/prometheus-cluster-exporter.service"
        mode: '0644'
        remote_src: yes

    - name: Copy SPEC file
      ansible.builtin.copy:
        src: "{{ source_path }}/rpm/prometheus-cluster-exporter.spec"
        dest: "{{ rpmbuild_home }}/SPECS/prometheus-cluster-exporter.spec"
        mode: '0644'
        remote_src: yes

- name: Update spec file and options file
  hosts: nodes
  become: false
  tasks:
    - name: Set Name in spec file
      ansible.builtin.replace:
        path: "{{ rpmbuild_home }}/SPECS/prometheus-cluster-exporter.spec"
        regexp: '^Name:\s+.*'
        replace: "Name:           {{ exporter_name }}"

    - name: Set Version in spec file
      ansible.builtin.replace:
        path: "{{ rpmbuild_home }}/SPECS/prometheus-cluster-exporter.spec"
        regexp: '^Version:\s+.*'
        replace: "Version:        {{ exporter_version }}"
    
    - name: Set Prometheus server and port in options
      ansible.builtin.lineinfile:
        path: "{{ rpmbuild_home }}/SOURCES/prometheus-cluster-exporter.options"
        regexp: '^OPTIONS='
        line: 'OPTIONS="--promserver={{ prom_server }} --port={{ listen_port }}"'
        backrefs: yes
    
- name: Build RPM package
  hosts: nodes
  become: false

  tasks:
    - name: Create RPM package
      ansible.builtin.command:
        cmd: rpmbuild -ba {{ rpmbuild_home }}/SPECS/prometheus-cluster-exporter.spec

- name: Copy built RPMs to local host
  hosts: nodes
  become: false
  tasks:
    - name: Find all RPM files in rpmbuild_home
      ansible.builtin.find:
        paths: "{{ rpmbuild_home }}"
        patterns: "*.rpm"
        recurse: yes
      register: rpm_files

    - name: Fetch RPM files to local host
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "./rpms/"   # local folder on your host where files will be copied
        flat: yes         # don't preserve remote folder structure
      loop: "{{ rpm_files.files }}"
